=== Arvolear/University/Web_technology/Lab8/book.dtd
<!ELEMENT book (page+)>
<!ELEMENT page (colont, content)>
<!ELEMENT colont ((topic | topic_1), (num_page | num_page_1))>
<!ELEMENT content (image*, image_description*, paragraph*, big_paragraph*)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT topic_1 (#PCDATA)>
<!ELEMENT num_page (#PCDATA)>
<!ELEMENT num_page_1 (#PCDATA)>
<!ELEMENT image_description (#PCDATA)>
<!ELEMENT paragraph ANY>
<!ELEMENT big_paragraph ANY>
<!ELEMENT centered ANY>
<!ELEMENT tabbed ANY>
<!ELEMENT mono ANY>
<!ELEMENT image EMPTY>
<!ELEMENT b (#PCDATA)>
<!ELEMENT br EMPTY>

<!ATTLIST page
    number CDATA #REQUIRED
>

=== Arvolear/University/Web_technology/Lab8/index.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE book SYSTEM "book.dtd">

<?xml-stylesheet type="text/css" href="main.css"?>

<book>
    <page number="1">
        <colont>
            <num_page>8</num_page>
            <topic>Тема 1</topic>            
        </colont>
        <content>
            <image/>
            <image_description>Рисунок 1.1. Объединение сетей в Интернет</image_description>
            <big_paragraph>
                <b>Веб-страница</b> – гипертекстовой ресурс Всемирной паутины, обычно написанный 
                на языке HTML. Веб-страница может содержать ссылки для перехода
                на другие страницы, а также изображения, медиафайлы, например звуковые
                файлы и видео, Flash-анимацию и т.п.
            </big_paragraph>
            <paragraph>
                Программа, демонстрирующая веб-страницу, называется <b>веб-браузер</b>. 
                Несколько веб-страниц, объединенных общей темой и дизайном, образуют <b>веб-сайт</b>.
            </paragraph>
            <big_paragraph>
                <b>Веб-сервер (HTTP-сервер)</b> – это программное обеспечение (ПО), предостав-
                ляющее доступ к сайтам. Наиболее популярными веб-серверами являются
                Apache (для ОС Windows и Unix) и Microsoft IIS (для Windows). Также веб-сервером 
                называют компьютер, на котором установлено такое ПО.
            </big_paragraph>
            <paragraph>
                URL (Uniform Resource Locator) – адрес ресурса.
                <br/>                
                Структура URL:
                <centered>
                    <mono>протокол :// пользователь : пароль @ хост : порт / путь ? запрос</mono>
                </centered>
            </paragraph>    
        </content>
    </page>
    <page number="2">
        <colont>
            <topic1>Содержание</topic1>   
            <num_page1>9</num_page1>                     
        </colont>
        <content>                           
            <paragraph>
                Некоторые элементы URL могут быть опущены. Чаще всего адрес имеет вид<br/>
                <mono>протокол :// хост / путь</mono>,
                <br/>            
                где <br/>
                <tabbed>
                    протокол – http, https, ftp, skype и др.<br/>
                    хост – доменное имя (или IP-адрес)<br/>
                    путь – местонахождение ресурса на хосте            
                </tabbed>
            </paragraph>
            <paragraph>
                Например: http://www.redut.ru/forum/index.php
                При помощи URL можно ссылаться на любой открытый ресурс, будь то
                страница, изображение, файл для загрузки и т.д.
            </paragraph>
            <paragraph>
                Для обращения к сайту используют <b>доменное имя</b>. Доменное имя состоит из
                нескольких доменов, разделенных точкой.<br/>
                Например:<br/>
                maps.google.com – означает, что домен третьего уровня maps входит в домен
                второго уровня google, который в свою очередь входит в домен первого
                (верхнего) уровня com.
            </paragraph>
            <paragraph>
                Домены верхнего уровня делятся на общие и географические. Общие домены
                предназначены для определенного класса организаций, например:<br/>
                .com – для коммерческих сайтов;<br/>
                .org – для некоммерческих организаций;<br/>
                .net – для сайтов, чья деятельность связана с Интернетом.
            </paragraph>
            <paragraph>
                Использование географического домена не всегда означает то, что сайт размещается 
                в соответствующей стране или имеет к ней какое-либо отношение.
                Например, многие телекомпании используют домен .tv островного государ-
                ства Тувалу.
            </paragraph>
            <paragraph>
                Помимо доменного имени для работы сайта необходим круглосуточно работающий 
                веб-сервер, способный выдержать большие нагрузки. Услуга размещения 
                веб-сайта на веб-сервере называется <b>хостингом</b>. Хостинг может быть
                платным или бесплатным. На платном хостинге, как правило, предоставляется 
                доменное имя второго уровня. За пользование хостингом и доменом взимается 
                абонентская плата. На бесплатном хостинге предоставляется доменное 
                имя третьего уровня (напр. example.narod.ru).
            </paragraph>
        </content>
    </page>
</book>
